//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoesEntities : DbContext
    {
        public ShoesEntities()
            : base("name=ShoesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Заказы> Заказы { get; set; }
        public DbSet<Пользователь> Пользователь { get; set; }
        public DbSet<ПунктВыдачи> ПунктВыдачи { get; set; }
        public DbSet<СоставЗаказа> СоставЗаказа { get; set; }
        public DbSet<Товары> Товары { get; set; }
    }
}
