//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public Заказы()
        {
            this.СоставЗаказа = new HashSet<СоставЗаказа>();
        }
    
        public int Код { get; set; }
        public Nullable<System.DateTime> ДатаЗаказа { get; set; }
        public Nullable<System.DateTime> ДатаДоставки { get; set; }
        public Nullable<int> КодПункта { get; set; }
        public Nullable<int> КодПользователя { get; set; }
        public Nullable<int> КодДляПолучения { get; set; }
        public string СтатусЗаказа { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual ПунктВыдачи ПунктВыдачи { get; set; }
        public virtual ICollection<СоставЗаказа> СоставЗаказа { get; set; }
    }
}
