//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public Пользователь()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int Код { get; set; }
        public string РольСотрудника { get; set; }
        public string ФИО { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        public virtual ICollection<Заказы> Заказы { get; set; }
    }
}
