//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставЗаказа
    {
        public int Код { get; set; }
        public Nullable<int> КодТовара { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> КодЗаказа { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
