//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        public Товары()
        {
            this.СоставЗаказа = new HashSet<СоставЗаказа>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public string ЕдиницаИзмерения { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string Поставщик { get; set; }
        public string Производитель { get; set; }
        public string Категория { get; set; }
        public Nullable<int> Скидка { get; set; }
        public Nullable<int> КоличествоНаСкладе { get; set; }
        public string Описание { get; set; }
        public byte[] Фото { get; set; }
    
        public virtual ICollection<СоставЗаказа> СоставЗаказа { get; set; }
    }
}
